# Production Environment Inventory
[data_platform]
# data-vm-01 ansible_host=10.11.1.10
# data-vm-02 ansible_host=10.11.1.11
# data-vm-03 ansible_host=10.11.1.12

[postgresql]
# pg-mgmt-01 ansible_host=10.11.1.20

[monitoring]
# mon-01 ansible_host=10.10.3.10

[data_platform:vars]
env=prod
azure_region=centralus

[all:vars]
ansible_python_interpreter=/usr/bin/python3
